# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        - VITE_URL_BACKEND=${VITE_URL_BACKEND}
        - VITE_PORT_FRONTEND=${VITE_PORT_FRONTEND}
        - VITE_URL_BACKEND_WS=${VITE_URL_BACKEND_WS}
    env_file:
      - .env
    ports:
      - "${VITE_PORT_FRONTEND}:3000"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT_BACKEND}:3000"
    volumes:
      - "${PATH_TO_DB}:/data"

  backend_websockets:
    build:
      context: ./backend_websockets
      dockerfile: ./Dockerfile
